### ISSUE TITLE
[Italic Bowtie] TypeError: Transformation matrices must be tuple instances, not Transform.

### ISSUE THREAD

**Issue by colinmford** [FontBureau/fbOpenTools#18]
Hi there, getting the following error in RF3 _Version 3.4b (build 2001101108)_ when trying to italicize a glyph with "Make Reference Layer" checked.

```
Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 96, in sendEvent_
  File "/Applications/RoboFont3.app/Contents/Resources/lib/python3.7/vanilla/vanillaBase.py", line 503, in action_
    self.callback(sender)
  File "ItalicBowtie.py", line 294, in italicizeCallback
  File "ItalicBowtie.py", line 170, in italicize
  File "ItalicBowtie.py", line 116, in makeReferenceLayer
  File "/Applications/RoboFont3.app/Contents/Resources/lib/python3.7/fontParts/base/deprecated.py", line 77, in transform
    self.transformBy(*args, **kwargs)
  File "/Applications/RoboFont3.app/Contents/Resources/lib/python3.7/fontParts/base/base.py", line 466, in transformBy
    matrix = normalizers.normalizeTransformationMatrix(matrix)
  File "/Applications/RoboFont3.app/Contents/Resources/lib/python3.7/fontParts/base/normalizers.py", line 1010, in normalizeTransformationMatrix
    "not %s." % type(value).__name__)
TypeError: Transformation matrices must be tuple instances, not Transform.
```
[Here's a link to the line](https://github.com/FontBureau/fbOpenTools/blob/f4ed6aeca6cfe5859a4e9515b1c9276debc59980/ItalicBowtie/ItalicBowtie.roboFontExt/lib/ItalicBowtie.py#L116).

**Comment by colinmford** [comment]
#19 Fixes this issue
